const Categories = [
  { nameEnglish: 'Allergists', nameSpanish: 'Alergólogos' },
  { nameEnglish: 'Cardiologists', nameSpanish: 'Cardiólogos' },
  { nameEnglish: 'General Surgeons', nameSpanish: 'Cirujanos Generales' },
  { nameEnglish: 'Plastic Surgeons', nameSpanish: 'Cirujanos Plásticos' },
  { nameEnglish: 'Dentists / Dentistry', nameSpanish: 'Dentistas / Odontología' },
  { nameEnglish: 'Dermatologists', nameSpanish: 'Dermatólogos' },
  { nameEnglish: 'Endocrinologists', nameSpanish: 'Endocrinólogos' },
  { nameEnglish: 'Physiotherapists', nameSpanish: 'Fisioterapeutas' },
  { nameEnglish: 'Gastroenterologists', nameSpanish: 'Gastroenterólogos' },
  { nameEnglish: 'Geriatricians', nameSpanish: 'Geriatras' },
  { nameEnglish: 'Gynecologists', nameSpanish: 'Ginecólogos' },
  { nameEnglish: 'Hematologists', nameSpanish: 'Hematólogos' },
  { nameEnglish: 'Hepatologists', nameSpanish: 'Hepatólogos' },
  { nameEnglish: 'General Medicine', nameSpanish: 'Medicina General' },
  { nameEnglish: 'Internal Medicine Physicians', nameSpanish: 'Médicos Internistas' },
  { nameEnglish: 'Nephrologists', nameSpanish: 'Nefrólogos' },
  { nameEnglish: 'Pulmonologists', nameSpanish: 'Neumólogos' },
  { nameEnglish: 'Neurologists', nameSpanish: 'Neurólogos' },
  { nameEnglish: 'Nutritionists', nameSpanish: 'Nutricionistas' },
  { nameEnglish: 'Ophthalmologists', nameSpanish: 'Oftalmólogos' },
  { nameEnglish: 'Oncologists', nameSpanish: 'Oncólogos' },
  { nameEnglish: 'Orthopedic Surgeons', nameSpanish: 'Cirujanos Ortopédicos' },
  { nameEnglish: 'Otorhinolaryngologists', nameSpanish: 'Otorrinolaringólogos' },
  { nameEnglish: 'Pediatricians', nameSpanish: 'Pediatras' },
  { nameEnglish: 'Proctologists', nameSpanish: 'Proctólogos' },
  { nameEnglish: 'Psychologists', nameSpanish: 'Psicólogos' },
  { nameEnglish: 'Psychiatrists', nameSpanish: 'Psiquiatras' },
  { nameEnglish: 'Radiologists', nameSpanish: 'Radiólogos' },
  { nameEnglish: 'Urologists', nameSpanish: 'Urólogos' },
  { nameEnglish: 'Veterinarians', nameSpanish: 'Veterinarios' },
];

module.exports = { Categories };
